Features realization
Reillyminat/DeliveryPrice pull request #1
Opened 2021-04-10 14:02 UTC by Reillyminat

2021-04-11 12:11 UTC, serhii-shkodenko requested changes
Ревью еще не закончено, скачаб посмотрю детальнее. Ты можешь пока поправить это.

2021-04-14 12:17 UTC, serhii-shkodenko requested changes
Выглядит хорошо, но нужно поправить еще эти небольшие моменты.

2021-04-14 12:17 UTC, serhii-shkodenko commented on DeliveryPrice/Program.cs
> +            int index = 0, infantsIterator = 0, childIterator = 0;
По сути тебе эти итераторы не нужны. Ты уже проверил, что все массивы имеют одинаковое количество элементов, поэтому достаточно знать один индекс.

2021-04-14 12:17 UTC, serhii-shkodenko commented on DeliveryPrice/Program.cs
> +                if (dest.Contains("Wayne Street"))
Лучше не сокращать слова, используемые в именах идентификаторов.

2021-04-14 12:17 UTC, serhii-shkodenko commented on DeliveryPrice/Program.cs
> +                resultPrices[index] *= percentDiscount;
Здесь ты узнаешь сумму скидки, а нужно узнать сумму к оплате. То есть от изначальной суммы отнять сумму скидки.

2021-04-14 13:52 UTC, Reillyminat commented on DeliveryPrice/Program.cs
> +                resultPrices[index] *= percentDiscount;
Я не совсем точно передал смысл переменной в её названии, на самом деле я изначально инициализирую её 1 и далее отнимаю % скидки, после чего перемножаю конечную цену на эту переменную. В итоге мы получаем именно цену с вычетом скидки. Переименовал для корректности

2021-04-15 20:09 UTC, serhii-shkodenko commented on DeliveryPrice/Program.cs
> +            List<decimal> modPrices = prices.ToList();
Не стоит помечать замечание как исправленное, если это не так. Далеко не всегда нужно соглашаться с тем, кто ревьюит код и его замечаниями. Для этого и нужны пулл реквесты, чтобы найти наиболее оптимальные способы воплощения задач. Лучше написать, что не согласен и аргументировать свою точку зрения почему.

2021-04-15 20:11 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-04-16 06:55 UTC, merged