Currency converter
Reillyminat/DeliveryPrice pull request #10
Opened 2021-06-09 16:16 UTC by Reillyminat

2021-06-12 14:32 UTC, serhii-shkodenko commented
Поправь, пожалуйста, мерж конфликты.

2021-06-14 14:47 UTC, serhii-shkodenko requested changes
Пока можно поправть это. Позже гляну еще раз.

2021-06-14 14:47 UTC, serhii-shkodenko commented on AppliancesModel/Models/AppliancesDistribution.cs
> +            cancellationToken = new CancellationToken();
Токен берется из источника, на котором в случае необходимости вызывается отмена.

2021-06-14 14:47 UTC, serhii-shkodenko commented on AppliancesModel/Models/ConverterService.cs
> +                Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-EN");
Насколько я понимаю, ты это делаешь, чтобы установить культуру для парсинга. Для этого нужно использовать `CultureInfo`.

2021-06-14 15:43 UTC, Reillyminat commented on AppliancesModel/Models/AppliancesDistribution.cs
> +            cancellationToken = new CancellationToken();
Я понимаю, просто так особо и не придумал адекватное условие завершения работы этого таска. Может стоит сделать какую-то проверку на время запроса к API и если оно превышено выкидывать токен остановки?

2021-06-21 21:24 UTC, merged