Model realization
Reillyminat/DeliveryPrice pull request #2
Opened 2021-04-16 08:52 UTC by Reillyminat

Model is based on appliances of 3 types: washer, refrigerator, kitchen stove. In main used methods to add new goods, show stock and make order (which shows price of chosen product and delete it from stock).

2021-04-18 13:08 UTC, serhii-shkodenko requested changes
Обрати внимание на поля, их нотацию и модификаторы доступа. Просмотри весь ПР, пожалуйста, я не везде оставил соответствующие комментарии.

2021-04-18 13:08 UTC, serhii-shkodenko commented on AppliancesModel/Program.cs
> +            //initial purchase of goods
Ознакомься с [конвенцией для комментариев](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#commenting-conventions).  Согласно ей, нужно писать:

`// Initial purchase of goods.`

2021-04-18 13:08 UTC, serhii-shkodenko commented on AppliancesModel/Program.cs
> +            public AppliancesStock type { get; set; }
Согласно конвенциям свйоства следует называть в `PascalCase`. Просмотри весь ПР, пожалуйста.

2021-04-18 13:08 UTC, serhii-shkodenko commented on AppliancesModel/Program.cs
> +                Console.WriteLine("Input name:");
Ввода-вывода в моделях не должно быть. Это противоречить SOLID, а конкретно Single Responsibility Principle.

2021-04-19 08:42 UTC, Reillyminat commented on AppliancesModel/Program.cs
> +            float height;
Заменил на свойства

2021-04-19 08:44 UTC, Reillyminat commented on AppliancesModel/Program.cs
> +                Console.WriteLine("Input name:");
Изменил концепцию модели, теперь заполнением свойств занимается отдельный обработчик, реализующий соответствующий интерфейс.

2021-04-22 20:03 UTC, serhii-shkodenko commented
В этом ПР часть файлов относится к третьему заданию и должна быть в соответсвующем задании. Однако ПР для третьего задания я не вижу. Кроме того, почему-то удалено первое задание. Я на встрече не говорил, что его нужно удалять.

2021-05-03 21:37 UTC, serhii-shkodenko commented
Чтобы получить аппрув:

1. Отмени удаление файла Program.cs, в котором находится первое задание. 
2. Удали все файлы, который не относятся ко второму заданию, то есть в этом ПР должны остаться только модели.

2021-05-04 07:40 UTC, Reillyminat commented
> Чтобы получить аппрув:
> 
> 1. Отмени удаление файла Program.cs, в котором находится первое задание.
> 2. Удали все файлы, который не относятся ко второму заданию, то есть в этом ПР должны остаться только модели.

Я удалил консольную часть и могу привести модели к их текущему состоянию в 4-й ветке, но есть ли смысл делать двойную работу, если потом произведется слияние веток и конфликты из ранних веток просто отсеются?

2021-05-14 18:49 UTC, serhii-shkodenko commented
> > Чтобы получить аппрув:
> > 
> > 1. Отмени удаление файла Program.cs, в котором находится первое задание.
> > 2. Удали все файлы, который не относятся ко второму заданию, то есть в этом ПР должны остаться только модели.
> 
> Я удалил консольную часть и могу привести модели к их текущему состоянию в 4-й ветке, но есть ли смысл делать двойную работу, если потом произведется слияние веток и конфликты из ранних веток просто отсеются?

Как я отмечал на встречах, в мерж конфликтах нет ничего экстраординарного. Каждый разработчик будет сталкиваться  с ними регулярно и поэтому нет ничего плохого в том, чтобы научиться их решать. Для этого, в том числе, мы и делаем этот проект, чтобы приобрести опыт в ситуации, максимально приближенной к реальной. 

Да, нет никакой нужды провоцировать такие мерж конфликты. На реальных проектах это достигается адекватной паралелизацией задач, когда один разработчки не мешает другому и его код не зависит на данный момент от кода, который еще находится в работе и не вмержен в главную сетку. 

О втоем подходе можно сказать, что:
1) он приведет к измненеию источника правды - с главной ветки, на ту, в которой ты работаешь, что разрушает любой git flow;
2) он в принципе не решает проблему - а просто переносит ее решение на более отдаленную перспективу, и соответственно грозит еще более глобальным мерж конфликтом;
3) в целом задача считается выполненной только после мержа соответвующей ветки в главную.

Приводить модели этого ПР к состоянию, которое есть в более поздних ветках, не нужно. Для этого служат последующие ПРы.

2021-05-15 07:11 UTC, Reillyminat commented
> > > Чтобы получить аппрув:
> > > 
> > > 1. Отмени удаление файла Program.cs, в котором находится первое задание.
> > > 2. Удали все файлы, который не относятся ко второму заданию, то есть в этом ПР должны остаться только модели.
> > 
> > 
> > Я удалил консольную часть и могу привести модели к их текущему состоянию в 4-й ветке, но есть ли смысл делать двойную работу, если потом произведется слияние веток и конфликты из ранних веток просто отсеются?
> 
> Как я отмечал на встречах, в мерж конфликтах нет ничего экстраординарного. Каждый разработчик будет сталкиваться с ними регулярно и поэтому нет ничего плохого в том, чтобы научиться их решать. Для этого, в том числе, мы и делаем этот проект, чтобы приобрести опыт в ситуации, максимально приближенной к реальной.
> 
> Да, нет никакой нужды провоцировать такие мерж конфликты. На реальных проектах это достигается адекватной паралелизацией задач, когда один разработчки не мешает другому и его код не зависит на данный момент от кода, который еще находится в работе и не вмержен в главную сетку.
> 
> О втоем подходе можно сказать, что:
> 
> 1. он приведет к измненеию источника правды - с главной ветки, на ту, в которой ты работаешь, что разрушает любой git flow;
> 2. он в принципе не решает проблему - а просто переносит ее решение на более отдаленную перспективу, и соответственно грозит еще более глобальным мерж конфликтом;
> 3. в целом задача считается выполненной только после мержа соответвующей ветки в главную.
> 
> Приводить модели этого ПР к состоянию, которое есть в более поздних ветках, не нужно. Для этого служат последующие ПРы.

Я понял, далее постараюсь быстрее делать ПР, чтобы не было таких ситуаций. Так что мне дальше делать, можно мержить в master?

2021-05-20 22:18 UTC, serhii-shkodenko approved these changes
Можно мержить.

2021-05-21 13:13 UTC, merged