Cache (Task 7)
Reillyminat/DeliveryPrice pull request #8
Opened 2021-06-02 18:40 UTC by Reillyminat

2021-06-12 14:31 UTC, serhii-shkodenko commented
Поправь, пожалуйста, мерж конфликты.

2021-06-12 18:34 UTC, serhii-shkodenko requested changes

2021-06-12 18:34 UTC, serhii-shkodenko commented on AppliancesModel/Models/AppliancesDistribution.cs
> +            cache = new Cache(stockContext);
Бизнес уровень не должен управлять иницилизацией кеша. Он только обращается к нему с запросами.

2021-06-12 18:34 UTC, serhii-shkodenko commented on AppliancesModel/Models/AppliancesDistribution.cs
> +            foreach (var item in stockNumbersDetail)
Ты здесь уверен, что из кеша вернется какое-то значение. Но оно там будет не всегда.

2021-06-12 18:34 UTC, serhii-shkodenko commented on AppliancesModel/Models/Cache.cs
> +                    var thread = new Thread(o =>
Удали это использование потока.

2021-06-12 18:34 UTC, serhii-shkodenko commented on AppliancesModel/Models/Cache.cs
> +                    copy = JsonSerialization.CreateDeepCopy((T)data);
Зачем это? Чего ты хочешь добиться?

2021-06-12 19:07 UTC, Reillyminat commented on AppliancesModel/Models/Cache.cs
> +                    copy = JsonSerialization.CreateDeepCopy((T)data);
Я инициирую запуск потока с целью инвалидации кэша через какое-то время. Соответственно, это позволит поддерживать его актуальность. Ну и поскольку в кэше должна хранится копия данных я и произвожу глубокое копирование через сериализацию. И вторую такую же копию я делал, чтобы поток внезапно не обнулил ссылку и не вызвал непредсказуемые ошибки, но сейчас я поправил и через флаг просто помечаю кэш устаревшим.

2021-06-12 19:26 UTC, Reillyminat commented on AppliancesModel/Models/AppliancesDistribution.cs
> +            foreach (var item in stockNumbersDetail)
Не совсем понимаю. Да, кэш может вернуть пустую коллекцию, если стока нет. Но при обращении в кэш мы всегда получим текущую копию стока. По крайней мере нулевых ссылок там быть не должно

2021-07-11 15:18 UTC, serhii-shkodenko commented
Пофикси, пожалуйста, мерж конфликты.

2021-07-11 15:31 UTC, serhii-shkodenko requested changes

2021-07-11 15:31 UTC, serhii-shkodenko commented on AppliancesModel/Models/Cache.cs
> +                    var dataTimeExistance = 100000;
Это существование в чем в секундах, минутах? Лучше прояснить это в имени переменной. Если тебе эта переменная нужно только, чтобы использовать в потоке, который ты создаешь ниже, то удали.

2021-07-11 15:31 UTC, serhii-shkodenko commented on AppliancesModel/Models/Cache.cs
> +                    copy = JsonSerialization.CreateDeepCopy((T)data);
Тебе не нужно создавать поток для инвалидации. Достаточно при создании сохранять время помещения в кеш и при чтении проверять, не устарело ли значение.

2021-07-12 16:50 UTC, serhii-shkodenko requested changes
Поправь эти замечания, пожлауйста, и будет апрув.

2021-07-12 16:50 UTC, serhii-shkodenko commented on AppliancesModel/Models/UserManager.cs
> +            cache = cacheProvider;
Два параметра из трех ты проверяешь на `null`, а почему с кешем так не поступаешь? Добавь, пожалуйста, проверку.

2021-07-12 16:50 UTC, serhii-shkodenko commented on AppliancesModel/Models/OrderManager.cs
> +        public OrderManager(IOrdersData data, IDataSerialization serializer, ICacheable cacheProvider)
Ты добавил в конструктор параметр, но входящий объект нигде не сохраняешь, поправь, пожалуйста.

2021-07-12 16:50 UTC, serhii-shkodenko commented on AppliancesModel/Models/AppliancesDistribution.cs
> +            cache = cacheProvider;
Нет проверки на null, как остальных параметров. Добавь, пожалуйста.

2021-08-08 16:07 UTC, merged